### PR TITLE
Templatize Channel to enable use of different schedulers

### PR DESCRIPTION
**Pull request by omerfirmak**
This can enable Channels to be used with vibe.d event loop without select
support. Templatizing select causes a bunch of template mess, which I didn't want
to go through at this point.

Using select will result in a runtime crash.

### CODE REVIEW

**Comment by omerfirmak** [comment]
nvm. this wont work. Vibe.d primitives does not provide most of the functionality we need.

**Comment by omerfirmak** [comment]
Wait, they do.

**Review by AndrejMitrovic — APPROVED** [review]
just needs param docs (maybe mention vibe.d support)

**Comment by omerfirmak** [comment]
I'll give this a try today and merge if it works as expected.

**Comment by omerfirmak** [comment]
This wont work without some wrappers around vibe.d primitives.

Mostly https://github.com/vibe-d/vibe-core/blob/0c1ea531b8495b754364f145acc2b612a4598864/source/vibe/core/sync.d#L984
and https://github.com/vibe-d/vibe-core/blob/0c1ea531b8495b754364f145acc2b612a4598864/source/vibe/core/sync.d#L326

Marking this as a draft until we actually need a `VibeChannel`

**Pull request closed without merging**
