### PR TITLE
Remove Scheduler interface, make 'receive' rely less on global state

### PR DESCRIPTION
**Pull request by Geod24**
A step further into removing global steps and having CSP instead of Actor model.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
In the last commit message:

> aren't cash accross

Did you mean `aren't cached across`?

**Comment by AndrejMitrovic** [comment]
Nice nice nice. I like this.

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
> Did you mean aren't cached across?

You don't have to fix it, I understood it. Want me to merge?

**Comment by Geod24** [comment]
Fixed the commit message.

**Pull request merged**
