### PR TITLE
Implement go channels

### PR DESCRIPTION
**Pull request by omerfirmak**

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]
Stylistic changes should usually go in their own commits, but let's get this in :)

**Comment by omerfirmak** [comment]
> Stylistic changes should usually go in their own commits, but let's get this in :)

I knew you would say that :)

**Comment by AndrejMitrovic** [comment]
So this doesn't require #95 first?

**Comment by AndrejMitrovic** [comment]
Ok I see, it's a subset.

**Pull request merged**
