### PR TITLE
Some minor refactoring and tweaks

### PR DESCRIPTION
**Pull request by Geod24**
I was working on fixing the issue we're seeing with `restart`, and those few things were in the way.

### CODE REVIEW

**Review by AndrejMitrovic — APPROVED** [review]
Looks good.

**Comment by AndrejMitrovic** [comment]
There's some nothrow errors in there.

**Comment by Geod24** [comment]
I'll let the attributes be inferred then, it's always done for nested functions anyway

**Comment by AndrejMitrovic** [comment]
> it's always done for nested functions anyway

Oh I didn't know that. But actually that makes perfect sense.

**Pull request merged**
